config/routes.rb
Rails.application.routes.draw do
  resources :tacticscards

  resources :attackcards

  resources :enemycards

  resources :gamestates

  root 'welcome#index'

  get 'rules' => 'welcome#rules'

end

app/models/attackcard.rb
class Attackcard < ActiveRecord::Base
end

app/controllers/attackcards_controller.rb
class AttackcardsController < ApplicationController
  before_action :set_attackcard, only: [:show, :edit, :update, :destroy]

  # GET /attackcards
  # GET /attackcards.json
  def index
    @attackcards = Attackcard.all
  end

  # GET /attackcards/1
  # GET /attackcards/1.json
  def show
  end

  # GET /attackcards/new
  def new
    @attackcard = Attackcard.new
  end

  # GET /attackcards/1/edit
  def edit
  end

  # POST /attackcards
  # POST /attackcards.json
  def create
    @attackcard = Attackcard.new(attackcard_params)

    respond_to do |format|
      if @attackcard.save
        format.html { redirect_to @attackcard, notice: 'Attackcard was successfully created.' }
        format.json { render :show, status: :created, location: @attackcard }
      else
        format.html { render :new }
        format.json { render json: @attackcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attackcards/1
  # PATCH/PUT /attackcards/1.json
  def update
    respond_to do |format|
      if @attackcard.update(attackcard_params)
        format.html { redirect_to @attackcard, notice: 'Attackcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @attackcard }
      else
        format.html { render :edit }
        format.json { render json: @attackcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attackcards/1
  # DELETE /attackcards/1.json
  def destroy
    @attackcard.destroy
    respond_to do |format|
      format.html { redirect_to attackcards_url, notice: 'Attackcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attackcard
      @attackcard = Attackcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attackcard_params
      params.require(:attackcard).permit(:name, :cost, :damage, :description)
    end
end

app/helpers/attackcards_helper.rb
module AttackcardsHelper
end

app/views/attackcards/_form.html.slim
= form_for @attackcard do |f|
  - if @attackcard.errors.any?
    #error_explanation
      h2 = "#{pluralize(@attackcard.errors.count, "error")} prohibited this attackcard from being saved:"
      ul
        - @attackcard.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost
    = f.number_field :cost
  .field
    = f.label :damage
    = f.number_field :damage
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/attackcards/edit.html.slim
h1 Editing attackcard

== render 'form'

= link_to 'Show', @attackcard
'|
= link_to 'Back', attackcards_path

app/views/attackcards/index.html.slim
h1 Attack Cards Reference

table.reftables
  thead
    tr
      th Name
      th Cost
      th Damage
      th Description

  tbody
    - @attackcards.each do |attackcard|
      tr
        td = attackcard.name
        td = attackcard.cost
        td = attackcard.damage
        td = attackcard.description

= link_to "back", root_path

app/views/attackcards/new.html.slim
h1 New attackcard

== render 'form'

= link_to 'Back', attackcards_path

app/views/attackcards/show.html.slim
p#notice = notice

p
  strong Name:
  = @attackcard.name
p
  strong Cost:
  = @attackcard.cost
p
  strong Damage:
  = @attackcard.damage
p
  strong Description:
  = @attackcard.description

= link_to 'Edit', edit_attackcard_path(@attackcard)
'|
= link_to 'Back', attackcards_path