config/routes.rb
Rails.application.routes.draw do
  resources :tacticscards

  resources :attackcards

  resources :enemycards

  resources :gamestates

  root 'welcome#index'

  get 'rules' => 'welcome#rules'

end

app/models/tacticscard.rb
class Tacticscard < ActiveRecord::Base
end

app/controllers/tacticscards_controller.rb
class TacticscardsController < ApplicationController
  before_action :set_tacticscard, only: [:show, :edit, :update, :destroy]

  # GET /tacticscards
  # GET /tacticscards.json
  def index
    @tacticscards = Tacticscard.all
  end

  # GET /tacticscards/1
  # GET /tacticscards/1.json
  def show
  end

  # GET /tacticscards/new
  def new
    @tacticscard = Tacticscard.new
  end

  # GET /tacticscards/1/edit
  def edit
  end

  # POST /tacticscards
  # POST /tacticscards.json
  def create
    @tacticscard = Tacticscard.new(tacticscard_params)

    respond_to do |format|
      if @tacticscard.save
        format.html { redirect_to @tacticscard, notice: 'Tacticscard was successfully created.' }
        format.json { render :show, status: :created, location: @tacticscard }
      else
        format.html { render :new }
        format.json { render json: @tacticscard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tacticscards/1
  # PATCH/PUT /tacticscards/1.json
  def update
    respond_to do |format|
      if @tacticscard.update(tacticscard_params)
        format.html { redirect_to @tacticscard, notice: 'Tacticscard was successfully updated.' }
        format.json { render :show, status: :ok, location: @tacticscard }
      else
        format.html { render :edit }
        format.json { render json: @tacticscard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacticscards/1
  # DELETE /tacticscards/1.json
  def destroy
    @tacticscard.destroy
    respond_to do |format|
      format.html { redirect_to tacticscards_url, notice: 'Tacticscard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tacticscard
      @tacticscard = Tacticscard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tacticscard_params
      params.require(:tacticscard).permit(:name, :cost, :description)
    end
end

app/helpers/tacticscards_helper.rb
module TacticscardsHelper
end

app/views/tacticscards/_form.html.slim
= form_for @tacticscard do |f|
  - if @tacticscard.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tacticscard.errors.count, "error")} prohibited this tacticscard from being saved:"
      ul
        - @tacticscard.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost
    = f.number_field :cost
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/tacticscards/edit.html.slim
h1 Editing tacticscard

== render 'form'

= link_to 'Show', @tacticscard
'|
= link_to 'Back', tacticscards_path

app/views/tacticscards/index.html.slim
h1 Tactics Cards Reference

table.reftables
  thead
    tr
      th Name
      th Cost
      th Description

  tbody
    - @tacticscards.each do |tacticscard|
      tr
        td = tacticscard.name
        td = tacticscard.cost
        td = tacticscard.description

= link_to "back", root_path

app/views/tacticscards/new.html.slim
h1 New tacticscard

== render 'form'

= link_to 'Back', tacticscards_path

app/views/tacticscards/show.html.slim
p#notice = notice

p
  strong Name:
  = @tacticscard.name
p
  strong Cost:
  = @tacticscard.cost
p
  strong Description:
  = @tacticscard.description

= link_to 'Edit', edit_tacticscard_path(@tacticscard)
'|
= link_to 'Back', tacticscards_path