config/routes.rb
Rails.application.routes.draw do
  resources :tacticscards

  resources :attackcards

  resources :enemycards

  resources :gamestates

  root 'welcome#index'

  get 'rules' => 'welcome#rules'

end

app/models/enemycard.rb
class Enemycard < ActiveRecord::Base
end

app/controllers/enemycards_controller.rb
class EnemycardsController < ApplicationController
  before_action :set_enemycard, only: [:show, :edit, :update, :destroy]

  # GET /enemycards
  # GET /enemycards.json
  def index
    @enemycards = Enemycard.all
  end

  # GET /enemycards/1
  # GET /enemycards/1.json
  def show
  end

  # GET /enemycards/new
  def new
    @enemycard = Enemycard.new
  end

  # GET /enemycards/1/edit
  def edit
  end

  # POST /enemycards
  # POST /enemycards.json
  def create
    @enemycard = Enemycard.new(enemycard_params)

    respond_to do |format|
      if @enemycard.save
        format.html { redirect_to @enemycard, notice: 'Enemycard was successfully created.' }
        format.json { render :show, status: :created, location: @enemycard }
      else
        format.html { render :new }
        format.json { render json: @enemycard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enemycards/1
  # PATCH/PUT /enemycards/1.json
  def update
    respond_to do |format|
      if @enemycard.update(enemycard_params)
        format.html { redirect_to @enemycard, notice: 'Enemycard was successfully updated.' }
        format.json { render :show, status: :ok, location: @enemycard }
      else
        format.html { render :edit }
        format.json { render json: @enemycard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enemycards/1
  # DELETE /enemycards/1.json
  def destroy
    @enemycard.destroy
    respond_to do |format|
      format.html { redirect_to enemycards_url, notice: 'Enemycard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enemycard
      @enemycard = Enemycard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enemycard_params
      params.require(:enemycard).permit(:name, :damage, :hp, :vp, :tp, :description)
    end
end

app/helpers/enemycards_helper.rb
module EnemycardsHelper
end

app/views/enemycards/_form.html.slim
= form_for @enemycard do |f|
  - if @enemycard.errors.any?
    #error_explanation
      h2 = "#{pluralize(@enemycard.errors.count, "error")} prohibited this enemycard from being saved:"
      ul
        - @enemycard.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :lvl
    = f.number_field :lvl
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :damage
    = f.number_field :damage
  .field
    = f.label :hp
    = f.number_field :hp
  .field
    = f.label :vp
    = f.number_field :vp
  .field
    = f.label :tp
    = f.number_field :tp
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/enemycards/edit.html.slim
h1 Editing enemycard

== render 'form'

= link_to 'Show', @enemycard
'|
= link_to 'Back', enemycards_path

app/views/enemycards/index.html.slim
h1 Enemy Cards Reference

table.reftables
  thead
    tr
      th Lvl
      th Name
      th Damage
      th Hp
      th Vp
      th Tp
      th Description

  tbody
    - @enemycards.each do |enemycard|
      tr
        td = enemycard.lvl
        td = enemycard.name
        td = enemycard.damage
        td = enemycard.hp
        td = enemycard.vp
        td = enemycard.tp
        td = enemycard.description

= link_to "back", root_path

app/views/enemycards/new.html.slim
h1 New enemycard

== render 'form'

= link_to 'Back', enemycards_path

app/views/enemycards/show.html.slim
p#notice = notice

p
  strong Lvl:
  = @enemycard.lvl
p
  strong Name:
  = @enemycard.name
p
  strong Damage:
  = @enemycard.damage
p
  strong Hp:
  = @enemycard.hp
p
  strong Vp:
  = @enemycard.vp
p
  strong Tp:
  = @enemycard.tp
p
  strong Description:
  = @enemycard.description

= link_to 'Edit', edit_enemycard_path(@enemycard)
'|
= link_to 'Back', enemycards_path