config/routes.rb
Rails.application.routes.draw do
  resources :tacticscards

  resources :attackcards

  resources :enemycards

  resources :gamestates

  root 'welcome#index'

  get 'rules' => 'welcome#rules'

end

app/models/gamestate.rb
class Gamestate < ActiveRecord::Base
end

app/controllers/gamestates_controller.rb
class GamestatesController < ApplicationController
  include GameHelper
  before_action :set_gamestate, only: [:show, :edit, :update, :destroy]

  # GET /gamestates
  # GET /gamestates.json
  def index
    @gamestates = Gamestate.all
  end

  # GET /gamestates/1
  # GET /gamestates/1.json
  def show
    @enemycards1 = Enemycard.where(lvl: 1)
    @enemycards2 = Enemycard.where(lvl: 2)
    @enemycards3 = Enemycard.where(lvl: 3)
    @attackcards = Attackcard.all
    @tacticscards = Tacticscard.all
  end

  # GET /gamestates/new
  def new
    @gamestate = Gamestate.new
  end

  # GET /gamestates/1/edit
  def edit
  end

  # POST /gamestates
  # POST /gamestates.json
  def create
    @gamestate = Gamestate.new(gamestate_params)
    sanitize!(@gamestate)

    respond_to do |format|
      if @gamestate.save
        format.html { redirect_to @gamestate}
        format.json { render :show, status: :created, location: @gamestate }
      else
        format.html { render :new }
        format.json { render json: @gamestate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamestates/1
  # PATCH/PUT /gamestates/1.json
  def update
    respond_to do |format|
      if @gamestate.update(gamestate_params)
        @gamestate.turns += 1
        @gamestate.save
        format.html { redirect_to @gamestate, notice: 'Gamestate was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamestate }
      else
        format.html { render :edit }
        format.json { render json: @gamestate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamestates/1
  # DELETE /gamestates/1.json
  def destroy
    @gamestate.destroy
    respond_to do |format|
      format.html { redirect_to gamestates_url, notice: 'Gamestate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamestate
      @gamestate = Gamestate.find(params[:id])
    end

    def sanitize!(state)
      state.victory_points = 0
      state.tech_points = 0
      state.hit_points = 10
      state.enemy_deck = 1
      state.hand = ""
      state.my_deck = "1 1 1 2 2 2 2 2 2 2"
      state.discard = ""
      state.turn_phase = 0
      state.turns = 0

      deal_starting_hand(state)
    end

      #shuffle takes a seed for rng
    def deal_starting_hand(state)
      deck_arr = str_to_arr(state.my_deck).shuffle!(random: Random.new(1))
      5.times do |card|
        state.hand += " " + deck_arr.shift.to_s
      end
      state.my_deck = arr_to_str(deck_arr)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamestate_params
      params.require(:gamestate).permit(:victory_points,:tech_points, :hit_points, :enemy_deck, :hand, :my_deck, :discard, :turn_phase, :turns)
    end
end

app/helpers/gamestates_helper.rb
module GamestatesHelper
end

app/views/gamestates/_enemypanel.slim
.enemy-card
  #rundiv
    p
      ' Run from the enemy, you take fire but escape...for now.
    button type="button" class="runaway" Run from the enemy!
  #enemypicture
    .enemypic
      = image_tag("agamemnon.png")
  #enemystats
    .enemycard
      table
        tr
          td width="80px" Name:
          td.name none
        tr
          td HP:
          td.hp 0
        tr
          td Damage:
          td.dam 0
        tr
          td TP:
          td.tp 0
        tr
          td VP:
          td.vp 0
        tr
          td text:
          td.text none
  #enemydecks
    p
      ' Enemy threat level
      span.enemylevel 0
  #enemycardsreference
    #ec1 datastuff="#{@enemycards1.to_json}"

    #ec2 datastuff="#{@enemycards2.to_json}"

    #ec3 datastuff="#{@enemycards3.to_json}"

app/views/gamestates/_form.html.slim
= form_for @gamestate do |f|
  - if @gamestate.errors.any?
    #error_explanation
      h2 = "#{pluralize(@gamestate.errors.count, "error")} prohibited this gamestate from being saved:"
      ul
        - @gamestate.errors.full_messages.each do |message|
          li = message
  .field
    = f.hidden_field :turns

  .actions = f.submit

app/views/gamestates/_infobar.html.slim
table#playerStats
  tr
    td width="120px" Hit Points
    td.playerhp width="30px" 10
  tr
    td Tech Points
    td.playertp 0
  tr
    td.vpcolor Victory Points
    td.playervp 0
  tr
    td turn
    td.playerturn 0
#playerdeckdiscard
  table#deckanddiscard
    tr
      td width="80px" Deck
      td.deckcount width="50px" 10
    tr
      td Discard
      td.discardcount 0

app/views/gamestates/_shop.html.slim
| Tech Shop, buy upgrades with Tech Points
#inventory
  table border="1"
    caption Attack Cards
    tr bgcolor="#FF0000"
      th Buy
      th Cost
      th Name
      th Damage
    - for card in @attackcards
      tr.body
        td
          form
            input class="atk#{card.id}" type="number" value="0" min="0" max="100" style="width:40px;"
        td #{card.cost}
        td #{card.name}
        td #{card.damage}
  table border="1"
    caption Tactics Cards
    tr bgcolor="#FFFF00"
      th Buy
      th Cost
      th Name
      th Text
    - for card in @tacticscards
      tr.body
        td
          form
            input class="tac#{card.id}" type="number" value="0" min="0" max="100" style="width:40px;"
        td #{card.cost}
        td #{card.name}
        td #{card.description}
#shopbuttons
  button type="button" class="cancelshop" Cancel
  button type="button" class="buyall" Buy Selected

app/views/gamestates/_userpanel.slim
#ac datastuff="#{@attackcards.to_json}"
#tc datastuff="#{@tacticscards.to_json}"

#playerhand
  button type="button" class="selectall"
    ' Select all
  button type="button" class="playselected"
    ' Play selected cards
  button type="button" class="shopbutton" Purchase tech
  button type="button" class="refillhand"
    ' Refill hand
  #playersCards

app/views/gamestates/edit.html.slim
h1 Editing gamestate

== render 'form'

= link_to 'Show', @gamestate
'|
= link_to 'Back', gamestates_path

app/views/gamestates/index.html.slim
h1 Listing gamestates

table
  thead
    tr
      th
      th
      th

  tbody
    - @gamestates.each do |gamestate|
      tr
        td = link_to 'Show', gamestate
        td = link_to 'Edit', edit_gamestate_path(gamestate)
        td = link_to 'Destroy', gamestate, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Gamestate', new_gamestate_path

app/views/gamestates/new.html.slim
h1 New gamestate

== render 'form'

= link_to 'Back', gamestates_path

app/views/gamestates/show.html.slim
#notice
  .titlebanner Welcome to DYLA, a space combat deck building game!
  button type="button" class="startnew" start new game
.gamenotices
  span.objectives
    ul
      li Play your cards to damage enemies and defeat them, or to save your own skin.
      li Earn Victory Points(VP) and Technology Points(TP) when you defeat the enemy.
      li Spend TP to purchase new upgrades/cards, which will be immediately available the next time you draw.
      li Enemies get noticably tougher every 5 VPs, reach 15 to win!

.top
  .enemypanel
    = render 'enemypanel'

  .gamelog
    | Game Log
    ul

  #techshop
    = render 'shop'

  #infobar
    = render 'infobar'

.userpanel
  = render 'userpanel'

= link_to 'Back', gamestates_path